version: '3.8'

services:
  traefik-reverseproxy:
    image: traefik:livarot
    hostname: traefik-reverseproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/traefik.toml:/traefik.toml
      - ./conf/traefik_dynamic.toml:/traefik_dynamic.toml
      - ./conf/acme.json:/acme.json
    networks:
      - web

networks:
  web:
    external: true
  internal:
    external: false